### ISSUE TITLE
Dealing with wind offshore in power_plants_status_quo() 

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#60]
In this [power plant task](https://github.com/openego/powerd-data/blob/5ec3aa0a7963e634e882d435fe1845a23b0cb575/src/egon/data/datasets/power_plants/__init__.py#LL929C1-L929C52) some improvements can be made:

- add some logging, especially when assigning generators with missing geoms in order to keep track of the number and capacity which might be of less data quality
- address wind_offshore in this context
- ...

**Comment by ClaraBuettner** [comment]
Wind offshore plants are also part of MaStR. I'm not sure if they are also imported to our tables. In test-mode, they are dropped because it is filtered by `fedeal_state=SchleswigHolstein` and the offshore plants have `federal_state='AusschliesslicheWirtschaftszone'.` As soon as the Germany run reached the power plants dataset we could have a look there.
